/**
 * Files → SuiteCRM in-context action.
 *
 * Registers a file action that appears in every file's action menu.
 * On click, mounts a small dialog for the user to pick which SuiteCRM
 * record to attach the file to; on save, POSTs to the existing
 * `logNote` endpoint with a note body that carries the Nextcloud
 * file's absolute URL (link-only mode — no file transfer, one source
 * of truth stays in Nextcloud).
 *
 * Also detects two "Talk artefact" cases and swaps the action label:
 *   - file lives under Talk's recording folder (`/Talk/Recording/…`)
 *   - file carries the "Generated by AI" system tag spreed applies to
 *     AI-generated summary uploads
 * — both get the label "Log this Talk artefact as a SuiteCRM Meeting
 * Note" so the intent is legible without changing the flow.
 *
 * Loaded via LoadAdditionalScriptsListener → `Util::addScript` fires
 * only while the Files app is rendering, so the script never mounts
 * on unrelated pages.
 *
 * @author Kim Haverblad
 */
import { registerFileAction } from '@nextcloud/files'
import { translate as t } from '@nextcloud/l10n'
import { createApp } from 'vue'
import FileToSuiteCRMDialog from './components/FileToSuiteCRMDialog.vue'

// Inline SVG for the action icon. Uses a bookmark-plus mark since
// "linking to a record" is closer to "bookmark this file against a
// record" than "attaching" (we don't upload the bytes).
const ICON_SVG_INLINE = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17 3H7c-1.1 0-2 .9-2 2v16l7-3 7 3V5c0-1.1-.9-2-2-2m0 15-5-2.18L7 18V5h10zm-4-14h-2v3H8v2h3v3h2v-3h3V7h-3z"/></svg>'

const TALK_RECORDING_PREFIX = '/Talk/Recording/'
const TALK_AI_TAG_ID = 'Generated by AI' // spreed's canonical system-tag label

/**
 *
 * @param node
 */
function isTalkArtefact(node) {
	if (typeof node.path === 'string' && node.path.startsWith(TALK_RECORDING_PREFIX)) {
		return true
	}
	// System tag inspection via the DAV property spreed / systemtags registers.
	// Attribute shape: `{ 'system-tag': 'tagname' | string[] | { text: string }[] }`
	// Read defensively — a missing system-tag attribute is the common case.
	const tags = node.attributes?.['system-tags']?.['system-tag']
	if (tags === undefined) {
		return false
	}
	const flattened = [tags].flat().map((t) => typeof t === 'string' ? t : t?.text || '')
	return flattened.includes(TALK_AI_TAG_ID)
}

/**
 *
 * @param node
 */
function openDialog(node) {
	// Mount a single-use Vue app on demand so we don't carry a hidden
	// dialog on every Files page render. Cleaned up in the close/save
	// callbacks. Matches how integration_openproject mounts its file
	// dialog. Only one instance active at a time — a defensive check
	// so a double-click doesn't stack two dialogs.
	const existing = document.getElementById('suitecrm-file-dialog-mount')
	if (existing) {
		return
	}
	const mount = document.createElement('div')
	mount.id = 'suitecrm-file-dialog-mount'
	document.body.appendChild(mount)

	const app = createApp(FileToSuiteCRMDialog, {
		fileName: node.basename,
		filePath: node.path,
		fileId: node.fileid,
		isTalkArtefact: isTalkArtefact(node),
		onClose: () => {
			app.unmount()
			mount.remove()
		},
	})
	app.mount(mount)
}

registerFileAction({
	id: 'suitecrm-link',

	// Callbacks take an ActionContext (`{ nodes, view }`) in the v4
	// registerFileAction API — plain-object form as used by
	// integration_openproject/src/filesPlugin/filesPlugin.js. The
	// v3 `new FileAction({...})` constructor form is NOT exported
	// by the currently-shipped `@nextcloud/files` runtime and would
	// throw `FileAction is not a constructor` on script load.
	displayName({ nodes }) {
		if (nodes.length === 1 && isTalkArtefact(nodes[0])) {
			return t('integration_suitecrm', 'Log this Talk artefact as a SuiteCRM Meeting Note')
		}
		return t('integration_suitecrm', 'Link to SuiteCRM record')
	},

	iconSvgInline: () => ICON_SVG_INLINE,

	enabled({ nodes, view }) {
		// Single-node action, only in the primary Files view. Batch
		// link is a follow-up feature; skipping it keeps the initial
		// UX simple (user picks one file, one dialog, one record).
		return nodes.length === 1 && view?.id === 'files'
	},

	async exec({ nodes }) {
		openDialog(nodes[0])
		// Return null: we handled the interaction ourselves via the
		// dialog; Files should not display any inline result.
		return null
	},

	order: 25,
})
